
--DROP DATABASE simucredito
use master
go
if exists(select * from sysdatabases where name='simucredito')
	begin
		drop database simucredito
	end

create database simucredito
GO
use simucredito
GO

CREATE TABLE profesion(
	ID_PROF INT IDENTITY(1,1) PRIMARY KEY, --EL PRIMERO 1 Y EL SEGUNDO SE SUMA
	NOMBRE_P VARCHAR(100)
)
INSERT PROFESION SELECT 'MEDICO' --1
INSERT PROFESION SELECT 'INGENIERO' --2
INSERT PROFESION SELECT 'ABOGADO' --3
INSERT PROFESION SELECT 'ENFERMERA' --4
INSERT PROFESION SELECT 'ADMINISTRADOR'--5
INSERT PROFESION SELECT 'MILITAR' --6
INSERT PROFESION SELECT 'POLICIA'--7
INSERT PROFESION SELECT 'COSMETOLOGA' --8
INSERT PROFESION SELECT 'INDEPENDIENTE' --9
INSERT PROFESION SELECT 'OTRO' --10

--SELECT * FROM PROFESION
--SELECT * FROM cliente
--------------Tratar de borrar tabla-----------------

------------------------------------------------------
create table cliente(
	RUT NUMERIC(9) PRIMARY KEY,
	DV CHAR(1),
	NOMBRE VARCHAR(100),
	APELLIDO1 VARCHAR(100),
	APELLIDO2 VARCHAR(100),
	FECHA_NAC DATE,
	ID_PROF INT foreign key references profesion(ID_PROF),
	SUELDO_LIQ numeric(10)

)
 INSERT CLIENTE (RUT,DV,NOMBRE,APELLIDO1,APELLIDO2,FECHA_NAC,SUELDO_LIQ,ID_PROF)
	values
		('27944949','5','MARIA','ARIAS','HERNANDEZ','1999-02-10','680000',9)

create table Credito(
	CODIGO INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100),
	TASA_I NUMERIC(2),
	EDAD_MAX NUMERIC(2),
	MONTO_MIN numeric(15),
	MONTO_MAX numeric(15),
	SUELDO_MIN numeric(15),
	PLAZO_MIN int,
	PLAZO_MAX int

)


INSERT Credito (NOMBRE,TASA_I,EDAD_MAX,MONTO_MIN,MONTO_MAX,SUELDO_MIN,PLAZO_MIN,PLAZO_MAX) VALUES ('Credito de Hipotecario',4,65,10000000,200000000,1000000,15,25) --1
INSERT Credito (NOMBRE,TASA_I,EDAD_MAX,MONTO_MIN,MONTO_MAX,SUELDO_MIN,PLAZO_MIN,PLAZO_MAX) VALUES ('Credito de Consumo',8,85,500000,10000000,600000,1,3) --2
INSERT Credito (NOMBRE,TASA_I,EDAD_MAX,MONTO_MIN,MONTO_MAX,SUELDO_MIN,PLAZO_MIN,PLAZO_MAX) VALUES ('Credito Automotriz',3,85,2000000,15000000,600000,1,6) --3


--select * from Credito
--select * from cliente
--validacion1
